DO NOT MERGE - debug for DPE failure

diff --git a/.github/workflows/build-test.yml b/.github/workflows/build-test.yml
--- a/.github/workflows/build-test.yml
+++ b/.github/workflows/build-test.yml
@@ -72,30 +72,30 @@ jobs:
             core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
             core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
 
-      - name: Check that Cargo.lock doesn't need to be updated
-          # Note: this isn't the same as checking that Cargo.lock is up to date
-          # (cargo update --locked), which makes sure that every package is the
-          # latest published version. This is just ensuring that every
-          # dependency has an entry in Cargo.lock that is compatible with the
-          # version requirements in all Cargo.toml files.
-        run: |
-          # This works because cargo tree requires a Cargo.lock with no required updates
-          cargo tree --locked > /dev/null || (
-            echo "Please include required changes to Cargo.lock in your pull request"
-            # Without the --locked flag, cargo will do the minimal possible update to Cargo.lock
-            cargo tree > /dev/null 2> /dev/null
-            # Print out the differences to ease debugging
-            git diff Cargo.lock
-            exit 1
-          )
+      # - name: Check that Cargo.lock doesn't need to be updated
+      #     # Note: this isn't the same as checking that Cargo.lock is up to date
+      #     # (cargo update --locked), which makes sure that every package is the
+      #     # latest published version. This is just ensuring that every
+      #     # dependency has an entry in Cargo.lock that is compatible with the
+      #     # version requirements in all Cargo.toml files.
+      #   run: |
+      #     # This works because cargo tree requires a Cargo.lock with no required updates
+      #     cargo tree --locked > /dev/null || (
+      #       echo "Please include required changes to Cargo.lock in your pull request"
+      #       # Without the --locked flag, cargo will do the minimal possible update to Cargo.lock
+      #       cargo tree > /dev/null 2> /dev/null
+      #       # Print out the differences to ease debugging
+      #       git diff Cargo.lock
+      #       exit 1
+      #     )
 
-      - name: Check source-code formatting (run "cargo fmt" if this fails)
-        run: |
-          cargo fmt --check --all
+      # - name: Check source-code formatting (run "cargo fmt" if this fails)
+      #   run: |
+      #     cargo fmt --check --all
 
-      - name: Check license headers
-        run: |
-          cargo run -p caliptra-file-header-fix --locked -- --check
+      # - name: Check license headers
+      #   run: |
+      #     cargo run -p caliptra-file-header-fix --locked -- --check
 
       - name: Build
         run: |
@@ -107,55 +107,55 @@ jobs:
           (cd rom/dev && ./build.sh)
           sccache --show-stats
 
-      # Clippy needs to build crates as part of the check, so do it after the
-      # build.
-      - name: Clippy lint check
-        run: |
-          # Clippy doesn't look at --config, so manually set RUSTFLAGS to the
-          # same as the build steps to avoid invalidating the cargo cache.
-          RUSTFLAGS="-Dwarnings" cargo clippy --locked --all-targets -- -D warnings
-          CARGO_TARGET_DIR=target RUSTFLAGS="-Dwarnings" cargo clippy --locked --all-targets --manifest-path ci-tools/fpga-boss/Cargo.toml -- -D warnings
+      # # Clippy needs to build crates as part of the check, so do it after the
+      # # build.
+      # - name: Clippy lint check
+      #   run: |
+      #     # Clippy doesn't look at --config, so manually set RUSTFLAGS to the
+      #     # same as the build steps to avoid invalidating the cargo cache.
+      #     RUSTFLAGS="-Dwarnings" cargo clippy --locked --all-targets -- -D warnings
+      #     CARGO_TARGET_DIR=target RUSTFLAGS="-Dwarnings" cargo clippy --locked --all-targets --manifest-path ci-tools/fpga-boss/Cargo.toml -- -D warnings
 
-      # As fuzzing targets are not part of the workspace, perform their tests explicitly.
-      - name: Build test fuzzing targets
-        # Intermittently fails and is too slow
-        if: false
-        run: |
-          rustup toolchain install nightly-2023-04-15
-          cargo +nightly-2023-04-15 install cargo-fuzz cargo-afl
-          for target in dpe/dpe/fuzz/ drivers/fuzz/ image/verify/fuzz/ x509/fuzz/; do
-            pushd $target; \
-            cargo fmt --check; \
-            # TODO: Depends on https://github.com/chipsalliance/caliptra-sw/issues/681
-            #cargo clippy; \
-            cargo +nightly-2023-04-15 fuzz build --features libfuzzer-sys; \
-            cargo +nightly-2023-04-15 afl build --features afl; \
-            popd; \
-          done
-          for target in drivers/fuzz/ image/verify/fuzz/; do
-            pushd $target; \
-            cargo +nightly-2023-04-15 fuzz build --features libfuzzer-sys,struct-aware; \
-            cargo +nightly-2023-04-15 afl build --features afl,struct-aware; \
-            popd; \
-          done
+      # # As fuzzing targets are not part of the workspace, perform their tests explicitly.
+      # - name: Build test fuzzing targets
+      #   # Intermittently fails and is too slow
+      #   if: false
+      #   run: |
+      #     rustup toolchain install nightly-2023-04-15
+      #     cargo +nightly-2023-04-15 install cargo-fuzz cargo-afl
+      #     for target in dpe/dpe/fuzz/ drivers/fuzz/ image/verify/fuzz/ x509/fuzz/; do
+      #       pushd $target; \
+      #       cargo fmt --check; \
+      #       # TODO: Depends on https://github.com/chipsalliance/caliptra-sw/issues/681
+      #       #cargo clippy; \
+      #       cargo +nightly-2023-04-15 fuzz build --features libfuzzer-sys; \
+      #       cargo +nightly-2023-04-15 afl build --features afl; \
+      #       popd; \
+      #     done
+      #     for target in drivers/fuzz/ image/verify/fuzz/; do
+      #       pushd $target; \
+      #       cargo +nightly-2023-04-15 fuzz build --features libfuzzer-sys,struct-aware; \
+      #       cargo +nightly-2023-04-15 afl build --features afl,struct-aware; \
+      #       popd; \
+      #     done
 
-      - name: Run tests
-        run: |
-          CPTRA_COVERAGE_PATH=/tmp cargo --config "$EXTRA_CARGO_CONFIG" test --locked
-          CPTRA_COVERAGE_PATH=/tmp cargo --config "$EXTRA_CARGO_CONFIG" run --manifest-path ./coverage/Cargo.toml
+      # - name: Run tests
+      #   run: |
+      #     CPTRA_COVERAGE_PATH=/tmp cargo --config "$EXTRA_CARGO_CONFIG" test --locked
+      #     CPTRA_COVERAGE_PATH=/tmp cargo --config "$EXTRA_CARGO_CONFIG" run --manifest-path ./coverage/Cargo.toml
 
-          CARGO_TARGET_DIR=target cargo --config "$EXTRA_CARGO_CONFIG" test --locked --manifest-path ci-tools/fpga-boss/Cargo.toml
-          sccache --show-stats
+      #     CARGO_TARGET_DIR=target cargo --config "$EXTRA_CARGO_CONFIG" test --locked --manifest-path ci-tools/fpga-boss/Cargo.toml
+      #     sccache --show-stats
 
-      - name: Run emulator conformance tests
-        run: |
-          sudo apt-get install gcc-riscv64-unknown-elf binutils-riscv64-unknown-elf
-          (cd /tmp/ && git clone --depth 1 --branch old-framework-2.x https://github.com/riscv-non-isa/riscv-arch-test)
-          cargo --config "$EXTRA_CARGO_CONFIG" run --locked -p compliance-test -- --test_root_path /tmp/riscv-arch-test
+      # - name: Run emulator conformance tests
+      #   run: |
+      #     sudo apt-get install gcc-riscv64-unknown-elf binutils-riscv64-unknown-elf
+      #     (cd /tmp/ && git clone --depth 1 --branch old-framework-2.x https://github.com/riscv-non-isa/riscv-arch-test)
+      #     cargo --config "$EXTRA_CARGO_CONFIG" run --locked -p compliance-test -- --test_root_path /tmp/riscv-arch-test
 
-      - name: ROM Makefile
-        run: |
-          (cd rom/dev && make run)         
+      # - name: ROM Makefile
+      #   run: |
+      #     (cd rom/dev && make run)         
          
       - name: Caliptra HW-Model C Binding Smoke Test
         run: |
